DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS CITIES;
DROP TABLE IF EXISTS MOVIES;
DROP TABLE IF EXISTS MOVIE_THEATRE;
DROP TABLE IF EXISTS MOVIE_SHOWS;
DROP TABLE IF EXISTS MOVIE_TICKETS;


CREATE TABLE USER_INFO (
    USER_ID INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME	VARCHAR(30)	NOT NULL,
    EMAIL	VARCHAR(100)	NOT NULL,
    PHONE_NUMBER VARCHAR(17) NOT NULL,
    CONSTRAINT un_email UNIQUE (email),
    CONSTRAINT un_number UNIQUE (phone_number)

);

CREATE TABLE CITIES (
    city_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    city_name VARCHAR(50) NOT NULL,
    state	VARCHAR(50)	NOT NULL,
);

CREATE TABLE MOVIES (
    movie_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    movie_name VARCHAR(50) NOT NULL,
    language VARCHAR(50) NOT NULL,
    Release_date VARCHAR(50) NOT NULL,
    genre VARCHAR(50) NOT NULL,
     CONSTRAINT c_movie UNIQUE (movie_name,language)
);


CREATE TABLE MOVIE_THEATRE (
    theatre_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    theatre_name VARCHAR(100) NOT NULL,
    address	VARCHAR(500) NOT NULL,
    theatre_owner INTEGER NOT NULL,
    city_id	INTEGER	NOT NULL,
    FOREIGN KEY(theatre_owner) REFERENCES USER_INFO(user_id) ,
    FOREIGN KEY(city_id) REFERENCES CITIES(city_id)
);

CREATE TABLE MOVIE_SHOWS (
    show_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    theatre_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    capacity INTEGER NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    FOREIGN KEY(theatre_id) REFERENCES MOVIE_THEATRE(theatre_id) ,
    FOREIGN KEY(movie_id) REFERENCES MOVIES(movie_id)

);
CREATE TABLE MOVIE_TICKETS (
    ticket_id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    show_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    booking_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    seat_numbers	VARCHAR(500) NOT NULL,
    CONSTRAINT ticket UNIQUE (show_id,user_id,booking_time),
    FOREIGN KEY(show_id) REFERENCES MOVIE_SHOWS(show_id) ,
    FOREIGN KEY(user_id) REFERENCES USER_INFO(user_id)
);

